### ISSUE TITLE
Cannot read property 'conversations' of undefined

### ISSUE THREAD

**Issue by ctleow** [TwilioDevEd/whatsapp-group-messaging#2]
Hi there, when i try to run your createConversation.js on Twilio Function, i ran into this error. It seems like the async methods are not working hence whenever it tries to read conversation object, it's undefined. Any chance you can rectify this? Thanks! 

UnhandledPromiseRejectionWarning: Unhandled promise rejection: TypeError: Cannot read property 'conversations' of undefined
    at Object.exports.handler (/var/task/handlers/ZN3270598fd650ba3edb91db5264aea6e5.js:7:43)
    at Object.exports.handler (/var/task/node_modules/runtime-handler/index.js:339:10)
    at Runtime.exports.handler (/var/task/runtime-handler.js:17:17)
    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:73:25)

**Comment by ctleow** [comment]
Hi, i resolved the issue above by setting the default twilio version to 3.80.0.

Apparently the default for in Function is 3.20.0 which is not recognising "conversation"

**Comment by maxouzeer** [comment]
Hello @ctleow can you share how you set the default twilio version to 3.80.0 ? Thanks!

**Comment by maxouzeer** [comment]
Ok got it, it's in the "Dependencies sections" of https://console.twilio.com/us1/service/functions/ - I just "edited" Twilio version to 3.80.0 and was able to generate a channel ID: "CHXXXxxXXXxxXXXCcccCC" when visiting https://whatsapp-group-xxXxxxxxxXxxxXxxx.twil.io/createConversation.
