### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection: TypeError: Cannot read property 'conversations' of undefined

### ISSUE THREAD

**Issue by phuclp00** [TwilioDevEd/whatsapp-group-messaging#4]
I got this error when running this code on the `Functions and Assets` service, did I mistake, or was something wrong?
```

UnhandledPromiseRejectionWarning: Unhandled promise rejection: TypeError: Cannot read property 'conversations' of undefined
    at Object.exports.handler (/var/task/handlers/ZN0c1cf1af2c789ece5ed01618fc27f39c.js:5:51)
    at Object.exports.handler (/var/task/node_modules/runtime-handler/index.js:339:10)
    at Runtime.exports.handler (/var/task/runtime-handler.js:17:17)
    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:74:25)
```

**Comment by carnivash** [comment]
I'm having the same error.

**Comment by ubinatus** [comment]
Take into account that the twilio client has changed. So replace any `client.conversations.conversations...` with `client.conversations.v1.conversations....`. 

Same for`client.sync.services...`, which should be `client.sync.v1.services...`

**Comment by Manishvaghasiya** [comment]
@phuclp00 @carnivash 

Could you please go into dependencies section of your [function](https://console.twilio.com/?frameUrl=/console/functions/overview/services) and set version of twilio library to latest available [v.4.21.1](https://github.com/twilio/twilio-node/releases/tag/4.21.0) and @twilio/runtime-handler to latest available version [v.1.3.0](https://www.twilio.com/docs/serverless/functions-assets/handler#versions) and give it a try?

**Comment by AskVinny** [comment]
I tried the fix from @Manishvaghasiya above and it resolved the issue. Note I needed to go up to v5.0.3  of twilio

**Comment by phuclp00** [comment]
It's work for me, @Manishvaghasiya. Thanks for your help!
